package main

type User struct {
	Id       int    `json:"id" form:"id"`
	Name     string `json:"name" form:"name"`
	Email    string `json:"email" form:"email"`
	Password string `json:"password" form:"password"`
}
type Bookmark struct {
	Id       int    `json:"id" form:"id"`
	IdRecipe int    `json:"idrecipe" form:"idrecipe"`
	Type     string `json:"type" form:"type"`
}
type dataRecipe struct {
	Id   int    `json:"id" form:"id"`
	Name string `json:"name" form:"name"`
	Url  string `json:"url" form:"url"`
}

type listFilter struct {
	Filter string `json:"filter" form:"filter"`
	Url    string `json:"url" form:"url"`
}


type Categories struct {
	Meals []struct {
		StrCategory string `json:"strCategory"`
	} `json:"meals"`
}
type Area struct {
	Meals []struct {
		StrArea string `json:"strArea"`
	} `json:"meals"`
}
type Filter struct {
	Meals []struct {
		StrMeal      string `json:"strMeal"`
		StrMealThumb string `json:"strMealThumb"`
		IDMeal       string `json:"idMeal"`
	} `json:"meals"`
}

type FilterDrink struct {
	Drinks []struct {
		StrDrink      string `json:"strDrink"`
		StrDrinkThumb string `json:"strDrinkThumb"`
		IDDrink       string `json:"idDrink"`
	} `json:"drinks"`
}

type AutoGenerated struct {
	Drinks []struct {
		StrDrink      string `json:"strDrink"`
		StrDrinkThumb string `json:"strDrinkThumb"`
		IDDrink       string `json:"idDrink"`
	} `json:"drinks"`
}

type Ingredient struct {
	Meals []struct {
		IDIngredient   string      `json:"idIngredient"`
		StrIngredient  string      `json:"strIngredient"`
		StrDescription string      `json:"strDescription"`
		StrType        interface{} `json:"strType"`
	} `json:"meals"`
}
type DrinkFilterCategory struct {
	Drinks []struct {
		StrCategory string `json:"strCategory"`
	} `json:"drinks"`
}

type DrinkFilterIngredient struct {
	Drinks []struct {
		StrIngredient1 string `json:"strIngredient1"`
	} `json:"drinks"`
}
type DescriptionDrinks struct {
	Drinks []struct {
		IDDrink                     string      `json:"idDrink"`
		StrDrink                    string      `json:"strDrink"`
		StrDrinkAlternate           interface{} `json:"strDrinkAlternate"`
		StrDrinkES                  interface{} `json:"strDrinkES"`
		StrDrinkDE                  interface{} `json:"strDrinkDE"`
		StrDrinkFR                  interface{} `json:"strDrinkFR"`
		StrDrinkZHHANS              interface{} `json:"strDrinkZH-HANS"`
		StrDrinkZHHANT              interface{} `json:"strDrinkZH-HANT"`
		StrTags                     string      `json:"strTags"`
		StrVideo                    interface{} `json:"strVideo"`
		StrCategory                 string      `json:"strCategory"`
		StrIBA                      string      `json:"strIBA"`
		StrAlcoholic                string      `json:"strAlcoholic"`
		StrGlass                    string      `json:"strGlass"`
		StrInstructions             string      `json:"strInstructions"`
		StrInstructionsES           interface{} `json:"strInstructionsES"`
		StrInstructionsDE           string      `json:"strInstructionsDE"`
		StrInstructionsFR           interface{} `json:"strInstructionsFR"`
		StrInstructionsZHHANS       interface{} `json:"strInstructionsZH-HANS"`
		StrInstructionsZHHANT       interface{} `json:"strInstructionsZH-HANT"`
		StrDrinkThumb               string      `json:"strDrinkThumb"`
		StrIngredient1              string      `json:"strIngredient1"`
		StrIngredient2              string      `json:"strIngredient2"`
		StrIngredient3              string      `json:"strIngredient3"`
		StrIngredient4              string      `json:"strIngredient4"`
		StrIngredient5              interface{} `json:"strIngredient5"`
		StrIngredient6              interface{} `json:"strIngredient6"`
		StrIngredient7              interface{} `json:"strIngredient7"`
		StrIngredient8              interface{} `json:"strIngredient8"`
		StrIngredient9              interface{} `json:"strIngredient9"`
		StrIngredient10             interface{} `json:"strIngredient10"`
		StrIngredient11             interface{} `json:"strIngredient11"`
		StrIngredient12             interface{} `json:"strIngredient12"`
		StrIngredient13             interface{} `json:"strIngredient13"`
		StrIngredient14             interface{} `json:"strIngredient14"`
		StrIngredient15             interface{} `json:"strIngredient15"`
		StrMeasure1                 string      `json:"strMeasure1"`
		StrMeasure2                 string      `json:"strMeasure2"`
		StrMeasure3                 string      `json:"strMeasure3"`
		StrMeasure4                 interface{} `json:"strMeasure4"`
		StrMeasure5                 interface{} `json:"strMeasure5"`
		StrMeasure6                 interface{} `json:"strMeasure6"`
		StrMeasure7                 interface{} `json:"strMeasure7"`
		StrMeasure8                 interface{} `json:"strMeasure8"`
		StrMeasure9                 interface{} `json:"strMeasure9"`
		StrMeasure10                interface{} `json:"strMeasure10"`
		StrMeasure11                interface{} `json:"strMeasure11"`
		StrMeasure12                interface{} `json:"strMeasure12"`
		StrMeasure13                interface{} `json:"strMeasure13"`
		StrMeasure14                interface{} `json:"strMeasure14"`
		StrMeasure15                interface{} `json:"strMeasure15"`
		StrCreativeCommonsConfirmed string      `json:"strCreativeCommonsConfirmed"`
		DateModified                string      `json:"dateModified"`
	} `json:"drinks"`
}

func main()  {
	
}